/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/models/gltf/bouee.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/bouee.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Torus001_0.geometry} material={materials.buoyyellow} rotation={[0, 0, Math.PI / 2]} scale={0.092} />
    </group>
  )
}

useGLTF.preload('/bouee.gltf')
