/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/gltf/vaa2.gltf 
*/

import React, { useRef } from "react";
import { useGLTF, useTexture } from "@react-three/drei";

import * as THREE from "three";

export function CompetitionVaaModel(props) {
  const { nodes, materials } = useGLTF("assets/models/gltf/vaa2.gltf");

  const texture = useTexture("assets/models/textures/vaaTextureImage2.png");

  const textureMaterial = new THREE.MeshStandardMaterial({
    map: texture,
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        name="Kayak_LP"
        geometry={nodes.Kayak_LP.geometry}
        material={textureMaterial}
        position={[-0.888, 0.394, 0.669]}
      />
    </group>
  );
}

useGLTF.preload("assets/models/gltf/vaa2.gltf");
