/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/models/gltf/pagaiev2.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function DefaultPagaieModel(props) {
  const { nodes, materials } = useGLTF("assets/models/gltf/pagaiev2.gltf");
  return (
    <group
      {...props}
      dispose={null}
      position={[0.25, 0.1, 2.5]}
      scale={[0.2, 0.2, 0.2]}
    >
      <group position={[4.515, 0.032, -0.237]} scale={[0.143, 0.174, 0.426]}>
        <mesh
          geometry={nodes.Icosphere001_1.geometry}
          material={materials["Wood Grip"]}
        />
        <mesh
          geometry={nodes.Icosphere001_2.geometry}
          material={materials.Wood}
        />
        <mesh
          geometry={nodes.Icosphere001_3.geometry}
          material={materials.Carbon}
        />
      </group>
      <mesh
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        position={[-4.949, 0.209, -0.176]}
        rotation={[Math.PI / 2, -1.414, Math.PI / 2]}
        scale={0.487}
      />
    </group>
  );
}

useGLTF.preload("assets/models/gltf/pagaiev2.gltf");
