/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\public\assets\models\gltf\tree.gltf 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Tree(props) {
  const { nodes, materials } = useGLTF("assets/models/gltf/tree.gltf");
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0]} scale={[0.35, 0.35, 0.35]}>
        <mesh geometry={nodes.Cube003.geometry} material={materials.bark} />
        <mesh
          geometry={nodes.Cube003_1.geometry}
          material={materials.coconut}
        />
        <mesh geometry={nodes.Cube003_2.geometry} material={materials.leaf} />
      </group>
    </group>
  );
}

useGLTF.preload("assets/models/gltf/tree.gltf");
