/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/assets/models/glb/vaa3.glb -k 
*/

import React, { forwardRef, useRef } from "react";
import { useGLTF } from "@react-three/drei";

export const CompetitionVaaModel = forwardRef((props, ref) => {
  const { nodes, materials } = useGLTF("assets/models/glb/vaa3.glb");
  return (
    <group {...props} dispose={null}>
      <group
        name="DEFAULT_curve_001_Mesh001"
        position={[0, 0.12, 0]}
        rotation={[Math.PI / 2, 0, Math.PI]}
        scale={0.313}
        ref={ref}
      >
        <mesh
          name="DEFAULT_curve_001_Mesh002"
          geometry={nodes.DEFAULT_curve_001_Mesh002.geometry}
          material={materials.vaaTexture}
        />
        <mesh
          name="DEFAULT_curve_001_Mesh002_1"
          geometry={nodes.DEFAULT_curve_001_Mesh002_1.geometry}
          material={materials.vaaInnerTexture}
        />
      </group>
    </group>
  );
});

useGLTF.preload("/vaa3.glb");
